
/****** Object:  Table [dbo].[Incidents]    Script Date: 6/21/2020 7:09:59 PM ******/
DROP TABLE [dbo].[Incidents]
GO

/****** Object:  Table [dbo].[Incidents]    Script Date: 6/21/2020 7:09:59 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Incidents](
	[active] [varchar](500) NULL,
	[activity_due] [varchar](500) NULL,
	[work_end] [varchar](500) NULL,
	[work_start] [varchar](500) NULL,
	[additional_assignee_list] [varchar](500) NULL,
	[comments] [varchar](500) NULL,
	[approval] [varchar](500) NULL,
	[approval_history] [varchar](500) NULL,
	[asset] [varchar](500) NULL,
	[assignment_group] [varchar](500) NULL,
	[attack_vector] [varchar](500) NULL,
	[automation_activity] [varchar](max) NULL,
	[billable] [varchar](500) NULL,
	[u_business_domain] [varchar](500) NULL,
	[department] [varchar](500) NULL,
	[business_duration] [varchar](500) NULL,
	[business_criticality] [varchar](500) NULL,
	[business_service] [varchar](500) NULL,
	[u_can_cancel] [varchar](500) NULL,
	[request_category] [varchar](500) NULL,
	[u_category] [varchar](500) NULL,
	[category] [varchar](500) NULL,
	[change_request] [varchar](500) NULL,
	[close_code] [varchar](500) NULL,
	[close_notes] [varchar](500) NULL,
	[closed_at] [varchar](500) NULL,
	[company] [varchar](500) NULL,
	[contract] [varchar](500) NULL,
	[correlation_display] [varchar](500) NULL,
	[knowledge] [varchar](500) NULL,
	[sys_created_on] [varchar](500) NULL,
	[u_doc_review] [varchar](500) NULL,
	[delivery_plan] [varchar](500) NULL,
	[delivery_task] [varchar](500) NULL,
	[dest_ip] [varchar](500) NULL,
	[sys_domain] [varchar](500) NULL,
	[due_date] [varchar](500) NULL,
	[calendar_duration] [varchar](500) NULL,
	[escalation] [varchar](500) NULL,
	[estimated_end] [varchar](500) NULL,
	[expected_end] [varchar](500) NULL,
	[u_external_reference_number] [varchar](500) NULL,
	[external_url] [varchar](500) NULL,
	[follow_up] [varchar](500) NULL,
	[u_fullfillment_system] [varchar](500) NULL,
	[u_fullfillment_system_id] [varchar](500) NULL,
	[group_list] [varchar](500) NULL,
	[impact] [varchar](500) NULL,
	[incident] [varchar](500) NULL,
	[initiated_from] [varchar](500) NULL,
	[is_catalog] [varchar](500) NULL,
	[location] [varchar](500) NULL,
	[made_sla] [varchar](500) NULL,
	[malware_url] [varchar](500) NULL,
	[malware_hash] [varchar](500) NULL,
	[opened_at] [varchar](500) NULL,
	[order] [varchar](500) NULL,
	[other_ioc] [varchar](500) NULL,
	[u_vendor_other] [varchar](500) NULL,
	[parent] [varchar](500) NULL,
	[parent_security_incident] [varchar](500) NULL,
	[pir] [varchar](500) NULL,
	[priority] [varchar](500) NULL,
	[special_access_write] [varchar](500) NULL,
	[problem] [varchar](500) NULL,
	[qualification_group] [varchar](500) NULL,
	[special_access_read] [varchar](500) NULL,
	[reassignment_count] [varchar](500) NULL,
	[referrer_url] [varchar](500) NULL,
	[rejection_goto] [varchar](500) NULL,
	[requested_due_by] [varchar](500) NULL,
	[u_vendor] [varchar](500) NULL,
	[resolve_notes] [varchar](500) NULL,
	[risk] [varchar](500) NULL,
	[risk_change] [varchar](500) NULL,
	[risk_score] [varchar](500) NULL,
	[risk_score_override] [varchar](500) NULL,
	[sla_due] [varchar](500) NULL,
	[expected_start] [varchar](500) NULL,
	[secure_notes] [varchar](500) NULL,
	[security_incident_self] [varchar](500) NULL,
	[security_tags] [varchar](500) NULL,
	[service_offering] [varchar](500) NULL,
	[severity] [varchar](500) NULL,
	[skills] [varchar](500) NULL,
	[contact_type] [varchar](500) NULL,
	[source_ip] [varchar](500) NULL,
	[spam] [varchar](500) NULL,
	[subcategory] [varchar](500) NULL,
	[substate] [varchar](500) NULL,
	[sla_suspended] [varchar](500) NULL,
	[sla_suspended_for] [varchar](500) NULL,
	[sla_suspended_on] [varchar](500) NULL,
	[sla_suspended_reason] [varchar](500) NULL,
	[sys_tags] [varchar](500) NULL,
	[task_created] [varchar](500) NULL,
	[sys_class_name] [varchar](500) NULL,
	[template] [varchar](500) NULL,
	[template_workflow_invoked] [varchar](500) NULL,
	[time_worked] [varchar](500) NULL,
	[sys_updated_on] [varchar](500) NULL,
	[sys_mod_count] [varchar](500) NULL,
	[upon_approval] [varchar](500) NULL,
	[upon_reject] [varchar](500) NULL,
	[urgency] [varchar](500) NULL,
	[user_input] [varchar](500) NULL,
	[vendor_reference] [varchar](500) NULL,
	[vulnerability] [varchar](500) NULL,
	[watch_list] [varchar](500) NULL,
	[wf_activity] [varchar](500) NULL,
	[correlation_id] [varchar](500) NULL,
	[supplier] [varchar](500) NULL,
	[number] [varchar](500) NULL,
	[state] [varchar](500) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


